version: '3'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - app_network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 uoftrade.wsgi:application
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: